# Defines stages which are to be executed
image: quay.io/pypa/manylinux2010_x86_64

stages:  
  - build_wheel
  - audit_wheel

build_wheel:  
  stage: build_wheel
  script:
    - mkdir /output
    - /opt/python/cp37-cp37m/bin/pip wheel .[GUI] -w /output

cache:
  paths:
    - /output

audit_wheel:
  stage: audit_wheel
  script:
    - auditwheel repair /output/onda*whl -w /output/audited

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - /output/audited/*

