# Defines stages which are to be executed
image: quay.io/pypa/manylinux2010_x86_64

stages:  
  - build_wheel
  - audit_wheel

build_wheel:  
  stage: build_wheel
  script:
    - /opt/python/cp37-cp37m/bin/pip wheel .[GUI] -w output/onda*whl
  artifacts:
    paths:
      - output/onda*whl

audit_wheel:
  stage: audit_wheel
  script:
    - auditwheel repair output/onda*whl -w output/repaired
  artifacts:
    paths:
      - output/repaired/onda*whl

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - output/repaired/onda*whl

