site_name: OnDA Monitor - v21.5.0
site_dir: ../docs/html
extra_css:
  - assets/css/extra.css
theme:
  name: material
  features:
    - navigation.top
  icon:
    logo: material/alpha-o-box-outline
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - def_list
  - mkdocs-click
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
copyright: Copyright &copy; 2020-2021 OM Development Team
repo_url: https://github.com/omdevteam/om
edit_uri: ''
repo_name: omdevteam/om
plugins:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
            members_order: source
            heading_level: 1
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["psana"] = mock()
            - sys.modules["mpi4py"] = mock()
  - search

nav:
  - What is OM?: index.md
  - Installing OM: installing_om.md
  - Running OM: running_om.md
  - Configuring OM: configuring_om.md
  - Advanced Documentation: advanced_documentation.md
  - The OM Development Team: the_om_development_team.md
  - Code Reference:
    - om:
      - __init__: reference/om/index.md
      - abcs:
        - __init__: reference/om/abcs/index.md
        - data_retrieval_layer: reference/om/abcs/data_retrieval_layer.md
        - parallelization_layer: reference/om/abcs/parallelization_layer.md
        - processing_layer: reference/om/abcs/processing_layer.md
      - algorithms:
        - __init__: reference/om/algorithms/index.md
        - crystallography: reference/om/algorithms/crystallography.md
        - generic: reference/om/algorithms/generic.md
        - xes: reference/om/algorithms/xes.md
      - data_retrieval_layer:
        - __init__: reference/om/data_retrieval_layer/index.md
        - data_event_handlers_asapo: reference/om/data_retrieval_layer/data_event_handlers_asapo.md
        - data_event_handlers_files: reference/om/data_retrieval_layer/data_event_handlers_files.md
        - data_event_handlers_http: reference/om/data_retrieval_layer/data_event_handlers_http.md
        - data_event_handlers_psana: reference/om/data_retrieval_layer/data_event_handlers_psana.md
        - data_event_handlers_zmq: reference/om/data_retrieval_layer/data_event_handlers_zmq.md
        - data_retrieval_asapo: reference/om/data_retrieval_layer/data_retrieval_asapo.md
        - data_retrieval_files: reference/om/data_retrieval_layer/data_retrieval_files.md
        - data_retrieval_http: reference/om/data_retrieval_layer/data_retrieval_http.md
        - data_retrieval_psana: reference/om/data_retrieval_layer/data_retrieval_psana.md
        - data_retrieval_zmq: reference/om/data_retrieval_layer/data_retrieval_zmq.md
        - data_sources_asapo: reference/om/data_retrieval_layer/data_sources_asapo.md
        - data_sources_files: reference/om/data_retrieval_layer/data_sources_files.md
        - data_sources_psana: reference/om/data_retrieval_layer/data_sources_psana.md
        - data_sources_generic: reference/om/data_retrieval_layer/data_sources_generic.md
        - data_sources_http: reference/om/data_retrieval_layer/data_sources_http.md
        - data_sources_zmq: reference/om/data_retrieval_layer/data_sources_zmq.md
        - frame_retrieval: reference/om/data_retrieval_layer/frame_retrieval.md
        - utils_generic: reference/om/data_retrieval_layer/utils_generic.md
      - graphical_interfaces:
        - __init__: reference/om/graphical_interfaces/index.md
        - common: reference/om/graphical_interfaces/common.md
        - crystallography_gui: reference/om/graphical_interfaces/crystallography_gui.md
        - crystallography_frame_viewer: reference/om/graphical_interfaces/crystallography_frame_viewer.md
        - crystallography_parameter_tweaker: reference/om/graphical_interfaces/crystallography_parameter_tweaker.md
        - xes_gui: reference/om/graphical_interfaces/xes_gui.md
      - lib:
        - __init__: reference/om/lib/index.md
        - peakfinder8_extension: reference/om/lib/peakfinder8_extension.md
      - parallelization_layer:
        - __init__: reference/om/parallelization_layer/index.md
        - mpi: reference/om/parallelization_layer/mpi.md
        - multiprocessing: reference/om/parallelization_layer/multiprocessing.md
      - processing_layer:
        - __init__: reference/om/processing_layer/index.md
        - cheetah: reference/om/processing_layer/cheetah.md
        - crystallography: reference/om/processing_layer/crystallography.md
        - testing: reference/om/processing_layer/testing.md
        - xes: reference/om/processing_layer/xes.md
      - utils:
        - __init__: reference/om/utils/index.md
        - crystfel_geometry: reference/om/utils/crystfel_geometry.md
        - exceptions: reference/om/utils/exceptions.md
        - hdf5_writers: reference/om/utils/hdf5_writers.md
        - parameters: reference/om/utils/parameters.md
        - rich_console: reference/om/utils/rich_console.md
        - zmq_gui: reference/om/utils/zmq_gui.md
        - zmq_collecting: reference/om/utils/zmq_collecting.md
      - monitor: reference/om/monitor.md
  - Quick Links:
    - OM's Configuration Parameters: parameters.md
    - OM's Error Messages: errors.md
    - Available Data Types For Each Data Event Handler: data.md
    - Example Geometry Files: geometry.md   
